# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a40fad3e40b6f5993d1c52190a6f9df2c690ee1e5c27faae410ee33e030bc36e3060a71cf15fa637d938a82c0992305d3969b054cff53d45f014d4b62bd298a0

test:
  secret_key_base: 94bca5bc8ea19d1092d771b65ba03dd6451af079ea0890fdd9e54f5708b63ca7928e58f66bceacae6baa5c9208ebf1a1e2b816a55020a824a55fe241affec8e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
